#ifndef __PROJECT_CONF_H__
#define __PROJECT_CONF_H__

#undef IEEE802154_CONF_PANID     //KANKER CONTIKI!!!

#define NETSTACK_CONF_RDC        nullrdc_driver
#define NETSTACK_CONF_MAC        csma_driver
#define NETSTACK_CONF_FRAMER     framer_802154
#define FRAME802154_CONF_VERSION FRAME802154_IEEE802154E_2012
#define IEEE802154_CONF_PANID    0xDEAD
#define NETSTACK_CONF_WITH_IPV4  0
#define NETSTACK_CONF_WITH_IPV6  0

#endif /* __PROJECT_CONF_H__ */
